### PR TITLE
Admin panel refactoring

### PR DESCRIPTION
**Pull request by ddavness**
We're bumping Bootstrap to the next major version (v4 -> v5), and that will require us to do some deeper changes to the admin panel front-end.

I'll take this opportunity to do a deeper facelift on the UI itself. We should see dark mode finally being properly implemented and some stuff that wasn't exactly playing nicely on mobile should be back... playing nicely with mobile devices.

### CODE REVIEW

**Comment by ddavness** [comment]
19 commits in - I figured out I'd give a little teaser on the new control panel look and feel?

It's not going to be anything huge where everything gets done upside down; In fact, you should be able to use the new panel just like you used the old one. But this one is more beautiful and actually kinda works on your phone, too. :wink:

**Feedback is welcome!** I'll keep you posted.

| Context | Old  | New |
| ------------- | ------------- | ------------- |
| **Login** | image | image |
| **Status Checks** | image | image |
| **TLS Certificates** | image | image |
| **Backups** | image | image |
| **PGP Keyring** | image | image |
| **WKD Management** | image | image |

**Comment by ddavness** [comment]
6 pages to go!

**Comment by ddavness** [comment]
So far, so good - some pages will need some deeper refactoring, but we've reached the point where everything works reasonably well.

Next commits will be targeted towards implementing proper dark mode.

**Comment by ddavness** [comment]
# Dark mode, your eyes will finally be able to rest :relieved:
Ok, this was a bit easier than expected. The admin panel will include a toggle so that you can switch between light and dark mode to your heart's content!

image

image

image

image

image

**Comment by ddavness** [comment]
I might be done for now!

There'll be a second refactoring phase on the entire codebase (covering admin panel AND the API) which won't be part of this PR.

**Comment by tenseoverflow** [comment]
Nice one!
The new admin panel looks gorgeous with that dark theme.

**Comment by ddavness** [comment]
Thanks! ^-^

**Comment by mannp** [comment]
Looks really great, thanks for your efforts 👍🏻

**Pull request merged**
